### PR TITLE
protobuf support (WIP)

### PR DESCRIPTION
**Pull request by jbenet**
tests fail atm

### CODE REVIEW

**Comment by jbenet** [comment]
@rht or @whyrusleeping, if you could take a look, would be nice. i'm likely doing something stupid with the types.

**Comment by whyrusleeping** [comment]
the canonical cbor stuff isnt here yet, so the cbor tests may fail, and it appears that the json encoder doesnt do canonical either (i get random failures there)

**Comment by jbenet** [comment]
json should be doing canonical, but may be the same error-- maybe can switch to a different encoder altogther there too

**Comment by jbenet** [comment]
@whyrusleeping thanks, this fixes protobuf support, it seems.

**Comment by jbenet** [comment]
@whyrusleeping or, maybe not? https://travis-ci.org/jbenet/go-multicodec/jobs/77369759#L132-L139

**Comment by jbenet** [comment]
thanks @whyrusleeping !

**Pull request merged**
